version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: employeest_be_web
    volumes:
      - .:/app
    ports:
      - "6969:8000"
    env_file:
      - ./.env
    restart: unless-stopped
