name: Django CI and Report

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Installs pytest, pytest-django, etc.
        pip install junit2html # For converting XML report to HTML

    - name: Prepare Environment File
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
        echo "QUICK_CHART_API_URL=${{ secrets.QUICK_CHART_API_URL }}" >> .env
        echo "DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}" >> .env
        echo "DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" >> .env
        echo "DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}" >> .env
        # Ensure your pytest.ini sets DJANGO_SETTINGS_MODULE

    - name: Create Migrations
      run: |
        python manage.py makemigrations

    - name: Run Tests with Pytest
      run: |
        mkdir -p test-results # Ensure the directory exists
        pytest --junitxml=test-results/results.xml

    - name: Convert Test Report to HTML
      if: always()
      run: |
        junit2html test-results/results.xml test-results/index.html

    - name: Upload Raw Test Report (XML Artifact)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: django-test-report-xml
        path: test-results/results.xml
        retention-days: 7

    - name: Upload HTML Test Report (HTML Artifact)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: django-test-report-html
        path: test-results/index.html
        retention-days: 7

    - name: Deploy Test Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-results